### ISSUE TITLE
Any progress here?

### ISSUE THREAD

**Issue by guoquan** [SCULX/leetcode_practice#1]
Think you have a plan to post two solutions every week. But it is yet empty here. What are you waiting for 😃

**Comment by SCULX** [comment]
I'm so sorry, because I'm not good at using Git, which has caused many errors and slowed down the progress. Only this time and no more.

**Comment by SCULX** [comment]
> Think you have a plan to post two solutions every week. But it is yet empty here. What are you waiting for 😃

I'm so sorry, because I'm not good at using Git, which has caused many errors and slowed down the progress. Only this time and no more.

**Comment by guoquan** [comment]
👀 Then that s (partially) why you d need this exercise.
