### ISSUE TITLE
Use a consistent branching model

### ISSUE THREAD

**Issue by guoquan** [SCULX/leetcode_practice#2]
Understanding how branches work is essential to work with git.
Be realized about you are working on which branch, and what are the roles of each of them.

Usually there is a default branch you want to show to other users, which is `main` by default "now". Legacy docs might refer to `master` due to some [historical reason](https://www.jumpingrivers.com/blog/git-moving-master-to-main/).
Am fine with either. Just be consistent, and let gh know by going to project setting somewhere.
gh is using `main`, while I see you r push something to `master`.

And you have a `mid` branch. Not sure what s the purpose of it. You can explain the role of each branch (that is your branching model) some where other users can see.
For branching models that are more commonly used, you might want to consult the following links
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
https://nvie.com/posts/a-successful-git-branching-model/
https://docs.github.com/en/get-started/quickstart/github-flow

Again, either model should work, just be consistent and declare somewhere so other users can understand.

**Comment by SCULX** [comment]
> Understanding how branches work is essential to work with git. Be realized about you are working on which branch, and what are the roles of each of them.
> 
> Usually there is a default branch you want to show to other users, which is `main` by default "now". Legacy docs might refer to `master` due to some [historical reason](https://www.jumpingrivers.com/blog/git-moving-master-to-main/). Am fine with either. Just be consistent, and let gh know by going to project setting somewhere. gh is using `main`, while I see you r push something to `master`.
> 
> And you have a `mid` branch. Not sure what s the purpose of it. You can explain the role of each branch (that is your branching model) some where other users can see. For branching models that are more commonly used, you might want to consult the following links https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow https://nvie.com/posts/a-successful-git-branching-model/ https://docs.github.com/en/get-started/quickstart/github-flow
> 
> Again, either model should work, just be consistent and declare somewhere so other users can understand.

Thank you very much for your suggestion and help. I am learning the relevant documents. Although I tried some methods, they all failed, so I still need more time to deal with these problems.

**Comment by guoquan** [comment]
So you don't close the issue until it is resolved. Leave it open until you don't need it.

**Comment by SCULX** [comment]
> So you don't close the issue until it is resolved. Leave it open until you don't need it.

I finally resolved this problem. It just because I haven't refreshed my login on GitHub Desktop, so the merge and push operations were always unsuccessful. Signing out the account and logging in again are the correct method.

**Comment by guoquan** [comment]
You still need to describe your branching model somehow. What is the role of `mid`? and `main`?

**Comment by SCULX** [comment]
> You still need to describe your branching model somehow. What is the role of `mid`? and `main`?

Sorry, now I get what you mean. I have explained the branches' role in README.md in the `main` branch.
