### ISSUE TITLE
Automating the testing

### ISSUE THREAD

**Issue by guoquan** [SCULX/leetcode_practice#22]
You are making progress 🔥 

I see your concern in testing the windows-based code on linux. But most of the source code won't depend on any OS thing.
If necessary, keep an OS dependent set of headers and make sure the source code for each solution is compatible with either windows or linux.
Then you may use a linux-compatible compiler in the gh action while still play with windows locally.

**Comment by guoquan** [comment]
Are you trying to address this on `makepipi` branch? Interesting, and what is the plan to merge it to the `main` branch?
I think you can explain the plan in the corresponding issue and keep people who are following it informed and see what is going on.

**Comment by SCULX** [comment]
The `makepipi` branch is almost useless and synchronized with the `main` branch. Initially, the `makepipi` branch was used for automatic testing by using Makefile files, but the GitHub Actions only allows for automatic testing on the `main` branch, so this branch is only used as a mark.

**Comment by SCULX** [comment]
> Are you trying to address this on `makepipi` branch? Interesting, and what is the plan to merge it to the `main` branch? I think you can explain the plan in the corresponding issue and keep people who are following it informed and see what is going on.

The `makepipi` branch is almost useless and synchronized with the `main` branch. Initially, the `makepipi` branch was used for automatic testing by using Makefile files, but the GitHub Actions only allows for automatic testing on the `main` branch, so this branch is only used as a mark.

**Comment by guoquan** [comment]
GitHub Actions can work with branches I belief https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters

**Comment by guoquan** [comment]
And the "Run workflow" trigger is only available to maintainers. Your guest wont be able to do what describe in main/README. Just directing people to the result (of auto testing) is fine.
