### ISSUE TITLE
Compilable solutions

### ISSUE THREAD

**Issue by guoquan** [SCULX/leetcode_practice#5]
It is great you are making progress and getting familiar with it. Let's be looking at something more fun.

Please consider making the solutions compilable and runnable for validation from the *command line*.
This is an essential step in making the automatic pipelines. You don't usually have UI when working with (economically efficient 😄 ) automatic things.

What is more important, it could be a lot more fun here.

For example, there could be a `makefile` managing the compiler commands, tackling problem selection, and even automatic testing.
Possible semantic:
```
# To compile the solution for question 812
make 812
# To test the solution for question 812
make 812-test
```

As you are using Visual Studio, you can figure out its compilers from manuals or google for it. 
You might need a sophisticated `configure` file or `cmake` to make it robust and feasible for different environment settings. Try to figure it out if you need it.

It might be a significant amount of work. So please consider doing it in a git branch, continue the current exercise with your current branch, and merge (with a nice PR) when the change is ready.

**Comment by guoquan** [comment]
Any thoughts about this? 😃

**Comment by SCULX** [comment]
> It is great you are making progress and getting familiar with it. Let's be looking at something more fun.
> 
> Please consider making the solutions compilable and runnable for validation from the _command line_. This is an essential step in making the automatic pipelines. You don't usually have UI when working with (economically efficient 😄 ) automatic things.
> 
> What is more important, it could be a lot more fun here.
> 
> For example, there could be a `makefile` managing the compiler commands, tackling problem selection, and even automatic testing. Possible semantic:
> 
> ```
> # To compile the solution for question 812
> make 812
> # To test the solution for question 812
> make 812-test
> ```
> 
> As you are using Visual Studio, you can figure out its compilers from manuals or google for it. You might need a sophisticated `configure` file or `cmake` to make it robust and feasible for different environment settings. Try to figure it out if you need it.
> 
> It might be a significant amount of work. So please consider doing it in a git branch, continue the current exercise with your current branch, and merge (with a nice PR) when the change is ready.

> Probably I solved it. But I'm not sure what the specific meaning is. I just provided the Makefile and the CI/CD provided by GitHub Actions based on the online example. 
>
> I originally used the Windows IDE, which is very convenient for development and the software development tool that most people choose. Why do I need to manually enter this operation on the command line?
>
> There are indeed many issues with porting this code on different platforms, so I have tried to minimize the number of files generated by visual studio 2019 automatic compilation. However, in general, shouldn't we first determine the platform before writing code based on its characteristics? If it needs to be ported to other platforms, it is very complex and I am not sure how the developers will handle it.
>
> I'm not sure why it's necessary to test these commands to check the running results. In the IDE, there are direct functional modules that allow developers to test the current state in the process.

**Comment by SCULX** [comment]
> Any thoughts about this? 😃

I'm sorry to answer so late. I'm a bit confused about this PR. So far I've only come up with two methods.
